import "./globals.css";
import "@mantine/core/styles.css";

import { Raleway } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import NavMenu from "./components/NavMenu";
import { GlobalProvider } from "@/context/postContext";
import { MantineProvider } from "@mantine/core";
import { ReactNode } from "react";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default async function RootLayout(props: RootLayoutProps) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
          defer
        ></script>
      </head>
      <body className={raleway.className}>
        <MantineProvider defaultColorScheme="auto" withGlobalClasses>
          <GlobalProvider>
            <SessionProvider session={session}>
              <NavMenu />
              {props.children}
            </SessionProvider>
          </GlobalProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
